#!/usr/bin/env python3
"""Generate crates/cli/src/numeric_locales.rs from glibc's compiled locales.

usage: generate_numeric_locales.py LOCPATH OUT_JSON OUT_RS

LOCPATH holds locales compiled with `localedef --no-archive -i NAME -f UTF-8
LOCPATH/NAME.UTF-8` for every UTF-8 entry of /usr/share/i18n/SUPPORTED
without a modifier, and every entry with one (whatever its character set)
compiled in UTF-8 as LOCPATH/NAME.UTF-8@MODIFIER, keyed NAME@MODIFIER: its
numbers can differ from its base's (nan_TW@latin groups by three, nan_TW by
four). For each, `locale -k LC_NUMERIC` (the glibc that compiled
them) gives the decimal point, thousands separator and grouping. Locales whose
decimal point is not one byte are omitted: Fastmash refuses them. OUT_JSON
keeps the raw values; OUT_RS is the table Fastmash compiles in, with the
names whose default character set is UTF-8 (compiled without a codeset
suffix, as SUPPORTED lists them), which glibc accepts without `.UTF-8`.
"""
import json
from pathlib import Path
import platform
import re
import subprocess
import sys


def glibc_version():
    return subprocess.check_output(['ldd', '--version'], text=True).splitlines()[0]


def read(locpath, name):
    env = {'LOCPATH': str(locpath), 'LC_ALL': name, 'PATH': '/usr/bin:/bin'}
    text = subprocess.check_output(['locale', '-k', 'LC_NUMERIC'], env=env, text=True)
    values = dict(re.findall(r'^([\w-]+)=(.*)$', text, re.M))
    return {
        'decimal_point': json.loads(values['decimal_point']),
        'thousands_sep': json.loads(values['thousands_sep']),
        # glibc prints group sizes separated by ';', with -1 for CHAR_MAX.
        'grouping': [int(size) for size in values['grouping'].split(';')] if values['grouping'] else [],
    }


def rust_bytes(text):
    return 'b"' + ''.join(f'\\x{b:02x}' for b in text.encode('utf-8')) + '"'


def grouping_bytes(sizes):
    # The C `grouping` string: one byte per size, CHAR_MAX (127) for -1.
    return 'b"' + ''.join(f'\\x{(127 if size == -1 else size):02x}' for size in sizes) + '"'


def main(locpath, out_json, out_rs):
    locpath = Path(locpath)
    # SUPPORTED names some UTF-8 locales without a codeset suffix (aa_ER).
    names = sorted(path.name for path in locpath.iterdir()
                   if path.is_dir() and not path.name.startswith('C.'))
    # Keys drop the codeset: `de_DE`, `sr_RS@latin`.
    table = {name.replace('.UTF-8', ''): read(locpath, name) for name in names}
    bare = sorted(name for name in names if '.' not in name)
    raw = {'glibc': glibc_version(), 'machine': platform.machine(), 'bare_utf8': bare,
           'locales': table}
    Path(out_json).write_text(json.dumps(raw, indent=1, ensure_ascii=False) + '\n', encoding='utf-8')
    rows = []
    omitted = []
    for name, v in sorted(table.items()):
        if len(v['decimal_point'].encode('utf-8')) != 1:
            omitted.append(name)
            continue
        rows.append(f'    (b"{name}", Profile::new({rust_bytes(v["decimal_point"])}[0], '
                    f'{rust_bytes(v["thousands_sep"])}, {grouping_bytes(v["grouping"])})),')
    header = f'''//! Generated by scripts/generate_numeric_locales.py from {raw["glibc"]} compiled
//! locales; do not edit. Number rules (decimal point, thousands separator and
//! grouping) of every glibc locale, with or without a modifier (compiled in
//! UTF-8), whose decimal point is one byte; the others are in `REFUSED`.
use fastmash_conversion::profile::Profile;

/// Sorted by name for binary search.
pub(super) static NUMERIC: &[(&[u8], Profile)] = &[
'''
    bare_rows = '\n'.join(f'    b"{name}",' for name in bare if name in dict(
        (row.split('"')[1], None) for row in rows))
    refused_rows = '\n'.join(f'    b"{name}",' for name in omitted)
    footer = ('\n];\n\n/// Names whose default character set is UTF-8, so glibc needs no\n'
              '/// codeset; sorted.\npub(super) static BARE_UTF8: &[&[u8]] = &[\n'
              + bare_rows + '\n];\n\n'
              '/// glibc locales whose decimal point is not one byte, whose numbers\n'
              '/// Fastmash refuses; sorted.\npub(super) static REFUSED: &[&[u8]] = &[\n'
              + refused_rows + '\n];\n')
    Path(out_rs).write_text(header + '\n'.join(rows) + footer, encoding='utf-8')
    print(f'{len(rows)} locales, omitted {omitted}')


if __name__ == '__main__':
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(*sys.argv[1:])
